### ISSUE TITLE
Brainstorm list of participants

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/LDP_raptors_proposal#2]

**Comment by FrancisBanville** [comment]
- [Andrew MacDonald](https://twitter.com/polesasunder?lang=fr), research professional with strong expertise in Bayesian models (Université de Sherbrooke)
- [Katherine Hébert](https://bios2.usherbrooke.ca/people/fellows/katherine-hebert/), PhD candidate studying biodiversity change (Université de Sherbrooke)
- [Juan Andrés Martínez-Lanfranco](https://bios2.usherbrooke.ca/people/fellows/juan-andres-martinez-lanfranco/), PhD candidate studying biodiversity patterns in South America (University of Alberta)
- [Gabriel Dansereau](https://bios2.usherbrooke.ca/people/fellows/gabriel-dansereau/), PhD candidate predicting beta diversity of ecological networks across space (Université de Montréal)
- [Salix Dubois](https://twitter.com/salixdubois), programmer and MSc student studying microbes on plants (Université du Québec à Montréal)
- [Tanya Strydom](https://tanyadoesscience.com/), PhD candidate developing predictive models of ecological networks and metawebs (Université de Montréal)
- [Camille Rondeau](https://ivado.ca/en/persons/camille-rondeau-saint-jean/), MSc student applying AI on the identification of bird songs (Université de Montréal)

**Comment by ToryHC** [comment]
**Dr. Carol Frost.** University of Alberta, [Rangeland Research Institute (RRI)](https://rri.ualberta.ca/). Studies how anthropogenic disturbances such as land management activities and invasive species impact biodiversity and species interactions, and how these changes to biotic communities in turn affect ecosystem processes, such as nutrient and energy flow through food webs, organic matter decomposition, plant pollination, and seed dispersal. My particular focus is on arthropods and their direct and indirect interactions, and in particular, taxa whose direct interactions with other species can be feasibly detected and quantified, such as plant-caterpillar-parasitoid interactions, ant-plant interactions, bee/wasp-parasitoid interactions, and plant-pollinator interactions.
**Dr. Troy Wellicome**. Senior Species At Risk Biologist at Environment and Climate Change Canada, University of Alberta.
