### ISSUE TITLE
Write work plan

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/LDP_raptors_proposal#5]
Work plan of activities: schedule of pre-meeting activities, agenda of the planned meetings, follow-up plan in order to reach the expected outcomes. As appropriate, please include the source of the data to be synthesized and methods of the analyses.

**Comment by AshSies** [comment]
**Pre-meeting activities**
One month away from in-person sessions: Zoom call and introductions, description of work plan/agenda, assigned pre-readings, set-up of the Github page (and other tools) that will be used during the working group sessions

**In-person meeting** 
_location_
U of R: cypress hills field site (I believe it was recently renovated?)

_length_
-One week? 
- One day introductions/presentations
- Organizer presentations; short talks to 
- Day 2/3/4 work 
- Breakout groups and their topics.. 
- Day 3 afternoon retreat?
- Day 4 begin brainstorming/prewriting the journal article?
- Day 5 wrap-up and next steps; confirm follow-up plans

_Accessibility considerations to weave into the work plan:_
-Hybrid working group meetings 
-Request accessible presentations from participants
-Location and venue: accessible by all members
-Food and other accommodations
-Working varied activities in to the day
-Breaks during workdays
-Childcare accommodations (hire centralized childcare, keep at same location as working group?)

**Follow-up plan**
Zoom call check-ins every two weeks? Goal date for article submission? Other avenues through which the working group outcomes can be shared?

**Comment by FrancisBanville** [comment]
That seems like a good plan! I have a few comments and suggestions:

- The organizers (us) could probably tidy the database prior to the meeting so we can start using it right away. 
- I don't think we should start writing the manuscript during the working group because of time limitations. I think we should rather focus on the methods and data analyses during the working group meetings. It would already be good to have some figures ready by the end of the week. But we should definitely discuss authorship and roles as well as a rough manuscript plan! 
- I like the idea of the afternoon retreat. Perhaps we should go to a place to see raptors? 
- The working group could take place somewhere in May 2023 (warmer temperatures - not sure if anyone wants to freeze in Saskatchewan in winter)
