### ISSUE TITLE
Write expected outcomes

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/LDP_raptors_proposal#6]
Expected outcomes (e.g., publications, white papers, open access databases, etc).

**Comment by AshSies** [comment]
Arena's initial draft and my first suggested revisions have been pushed 😄

**Comment by FrancisBanville** [comment]
The essential seems there! However, I'm not sure if it's useful to write an R package since we'll only do data analyses. We won't implement a new set of methods or functions that others can use (unless I misunderstood the objective of the working group). Should we also say something about recommending a set of actions to protect raptor populations in the prairies? Or perhaps a map of the areas where raptor populations are the most vulnerable / a map of where they are expected to be in the future could be an interesting outcome as well.

**Comment by AshSies** [comment]
I like your idea to add a set of recommended actions/guidelines for protecting raptors! And the maps you suggest would also be excellent.
