### ISSUE TITLE
Write EDI considerations

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/LDP_raptors_proposal#8]
A maximum 1-page supplement that addresses EDI considerations and a plan for authorship for any manuscripts that are generated from the working group. In this supplement, please clearly identify the steps that will be taken to ensure broad representation and participation by diverse groups (e.g. include a plan for development of a code of conduct). Authorship considerations should explicitly state how authorship on manuscripts will be determined.

**Comment by FrancisBanville** [comment]
These are my ideas so far:

### EDI considerations
- General statement about the importance of EDI
- Diversity of participants (gender parity, sociocultural background, domain of expertise, university)
- More funding to individuals from a marginalized group 
- Priority to students and early-career scientists 
- Childcare service 
- Possibility to attend the working group meetings remotely 
- Code of conduct including strong inclusivity principles (everyone can suggest changes and has to sign it)
- Reporting mechanisms 
- Activities promoting the participation of everyone
- Indigenous considerations (share of knowledge)
- EDI formation for all organizers 

### Authorship plan 
- Authorship grid 
- Level of implication and roles discussed prior to the writing of the manuscript

Any suggestions?

**Comment by AshSies** [comment]
These all look great! Perhaps we could also mention some of the accessibility considerations we will make for the working group, and how they promote/support inclusivity. For example we could mention the following (all of these come from the neurodivergence and inclusivity portion of our 5th lecture): 

- Offering quiet break spaces
- Planning movement breaks and welcoming flexible seating
- Allowing use of fidgets etc.

These also could (and probably should) be mentioned in the work plan section!

**Comment by FrancisBanville** [comment]
https://www.whose.land/en/

**Comment by spflaman** [comment]
Here are some First Nations communities that we could collaborate with throughout the working group:
- Kainai (Blood) Nation, Alberta (this is closer to BC border though)
- Piikani Nation, Alberta (also closer to BC border)
- Nekaneet Cree Nation, SW Saskatchewan
- Wood Mountain Lakota First Nation, Central-South Saskatchewan
- Ocean Man First Nation, SE Saskatchewan
- White Bear First Nations, SE Saskatchewan
- Pheasant Rump Nakota First Nation, SE Saskatchewan
- Swan Lake First Nation, SW-Central Manitoba
- Roseau River Anishinabe First Nation, SE-Central Manitoba

This is the interactive map I used to find the location of these, for the reference section:
https://geo.aadnc-aandc.gc.ca/cippn-fnpim/index-eng.html
